-- 1번 문제
SELECT STUDENT_NAME AS 학생이름 ,STUDENT_ADDRESS AS 주소지
FROM tb_student
order by  학생이름;

-- 2번 문제 
SELECT 
    STUDENT_NAME,
    STUDENT_SSN,
    YEAR(CURDATE()) - 
        CASE 
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('1', '2') THEN 1900 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('3', '4') THEN 2000 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
        END AS 나이
FROM tb_student
WHERE ABSENCE_YN = 'Y'
ORDER BY 나이;

-- 3번 문제
SELECT STUDENT_NAME,STUDENT_NO,STUDENT_ADDRESS
FROM tb_student
WHERE (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
  AND ENTRANCE_DATE LIKE '202%'
ORDER BY STUDENT_NAME ASC;

-- 4번 문제
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM tb_department A JOIN tb_professor B ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

