use employee;

-- 1번문제
SELECT EMP_NAME
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE
					FROM EMPLOYEE
					WHERE EMP_NAME = '노옹철'
);

-- 2번 문제
SELECT EMP_ID,EMP_NAME,JOB_CODE,SALARY
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY)
				FROM EMPLOYEE
				);
                
-- 3번 문제
	SELECT E.EMP_ID,E.EMP_NAME,J.JOB_NAME,E.SALARY
	 FROM  EMPLOYEE E JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
     WHERE E.SALARY>(SELECT SALARY
					FROM EMPLOYEE
					WHERE EMP_NAME = '노옹철'
					);
                    
-- 4번 문제


SELECT E.EMP_ID,E.EMP_NAME,J.JOB_NAME,E.SALARY,HIRE_DATE
FROM  EMPLOYEE E JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SALARY = (SELECT MIN(SALARY)
				FROM EMPLOYEE
				);
                
-- 5번 문제
SELECT E.EMP_NAME,J.JOB_NAME,E.SALARY
FROM  EMPLOYEE E JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE  SALARY IN (SELECT MAX(SALARY) AS 최고급여
				FROM EMPLOYEE
				GROUP BY DEPT_CODE
				)
GROUP BY E.EMP_NAME,J.JOB_NAME,E.SALARY;

-- 6번 문제

SELECT E.EMP_ID AS'관리자사번',E.EMP_NAME AS'관리자이름',J.JOB_NAME AS '관리자부서명'
FROM EMPLOYEE E JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE MANAGER_ID IS NOT NULL

UNION                
