use chundb;
-- 1번 문제
SELECT STUDENT_NAME AS 학생이름 ,STUDENT_ADDRESS AS 주소지
FROM tb_student
order by  학생이름;

-- 2번 문제 
SELECT 
    STUDENT_NAME,
    STUDENT_SSN,
    YEAR(CURDATE()) - 
        CASE 
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('1', '2') THEN 1900 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('3', '4') THEN 2000 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
        END AS 나이
FROM tb_student
WHERE ABSENCE_YN = 'Y'
ORDER BY 나이;

-- 3번 문제
SELECT STUDENT_NAME,STUDENT_NO,STUDENT_ADDRESS
FROM tb_student
WHERE STUDENT_ADDRESS LIKE '%강원%' OR STUDENT_ADDRESS LIKE '%경기%'
  AND ENTRANCE_DATE LIKE '202%'
ORDER BY STUDENT_NAME ASC;

-- 4번 문제
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM tb_department A JOIN tb_professor B ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

-- 9번 문제 
SELECT DISTINCT C.CLASS_NAME, P.PROFESSOR_NAME
FROM tb_class C JOIN tb_professor P ON C.DEPARTMENT_NO = P.DEPARTMENT_NO;

SELECT DISTINCT C.CLASS_NAME AS "과목이름", 
				P.PROFESSOR_NAME AS "교수이름"
FROM tb_class C LEFT JOIN tb_professor P ON C.DEPARTMENT_NO = P.DEPARTMENT_NO
WHERE P.PROFESSOR_NAME IS NOT NULL
ORDER BY C.CLASS_NAME ASC;

SELECT DISTINCT C.CLASS_NAME AS "과목이름", 
				P.PROFESSOR_NAME AS "교수이름"
FROM tb_professor P LEFT JOIN tb_class C ON P.DEPARTMENT_NO = C.DEPARTMENT_NO
WHERE C.CLASS_NAME IS NOT NULL AND P.PROFESSOR_NAME IS NOT NULL
ORDER BY C.CLASS_NAME ASC;

SELECT CLASS_NAME AS '과목이름', PROFESSOR_NAME AS '교수이름'
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR CP ON (CP.CLASS_NO = C.CLASS_NO)
JOIN TB_PROFESSOR P ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
ORDER BY C.CLASS_NAME ASC;








