-- 1번 문제
SELECT   STUDENT_NO AS 학번
		,STUDENT_NAME AS 이름
        ,ENTRANCE_DATE AS 입학년도
FROM tb_student A JOIN tb_department B ON A.DEPARTMENT_NO = B.DEPARTMENT_NO 
WHERE B.DEPARTMENT_NAME = '영어영문학과' AND B.DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2번 문제
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM tb_professor
WHERE PROFESSOR_NAME NOT like '___';

-- 3번 문제
SELECT  PROFESSOR_NAME AS 교수이름,
(YEAR(CURDATE()) - YEAR(STR_TO_DATE(CONCAT('19', SUBSTRING(PROFESSOR_SSN, 1, 6)), '%Y%m%d'))) -1 AS 만나이  -- CURDATE: 현재 날짜 , CONCAT : 문자열합치기, STR_TO_DATE:(문자열,변환할 DATE 형식)
FROM tb_professor
WHERE PROFESSOR_SSN like '_______1%'
ORDER BY 만나이;

-- 4번 문제
SELECT SUBSTRING(PROFESSOR_NAME,2,2) AS 이름
FROM tb_professor;

-- 5번 문제 
SELECT STUDENT_NO,STUDENT_NAME
FROM tb_student
WHERE ENTRANCE_DATE-STR_TO_DATE(SUBSTRING(STUDENT_SSN, 1, 6),'%Y%m%d');


-- 7 데이터포멧과 STR TO DATE 사용

SELECT STUDENT_NO,STUDENT_NAME, SUBSTRING(ENTRANCE_DATE, 1, 4)-CONCAT('19', SUBSTRING(STUDENT_SSN, 1, 2)) AS '입학나이'
FROM tb_student
WHERE SUBSTRING(ENTRANCE_DATE, 1, 4)-CONCAT('19', 'SUBSTRING(STUDENT_SSN, 1, 2') > 19 ;

SELECT CAST CONCAT('19', SUBSTRING(STUDENT_SSN, 1, 2))
FROM tb_student;
