-- 1번 문제
SELECT STUDENT_NAME AS 학생이름 ,STUDENT_ADDRESS AS 주소지
FROM tb_student
order by  학생이름;

-- 2번 문제 
SELECT 
    STUDENT_NAME,
    STUDENT_SSN,
    YEAR(CURDATE()) - 
        CASE 
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('1', '2') THEN 1900 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
            WHEN SUBSTRING(STUDENT_SSN, 8, 1) IN ('3', '4') THEN 2000 + CAST(SUBSTRING(STUDENT_SSN, 1, 2) AS UNSIGNED)
        END AS 나이
FROM tb_student
WHERE ABSENCE_YN = 'Y'
ORDER BY 나이 ASC;