-- 1번 문제
SELECT  DEPARTMENT_NAME
		,CATEGORY
FROM tb_department;

-- 2번 문제
SELECT   DEPARTMENT_NAME
		,CAPACITY
FROM tb_department;

-- 3번 문제
SELECT A.STUDENT_NAME
FROM tb_student A JOIN tb_department B ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '국어국문학과' AND STUDENT_SSN like '_______2%' AND ABSENCE_YN = 'Y';

-- 4번 문제
SELECT STUDENT_NAME
FROM tb_student
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119');

-- 5번 문제
SELECT DEPARTMENT_NAME,CATEGORY 
FROM tb_department
WHERE CAPACITY between 20 AND 30;

-- 6번 문제

SELECT PROFESSOR_NAME 
FROM tb_professor 
WHERE DEPARTMENT_NO IS NULL;

-- 7번 문제
SELECT STUDENT_NAME
FROM tb_student
WHERE DEPARTMENT_NO IS NULL;

-- 8번 문제
SELECT CLASS_NO
FROM tb_class
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번 문제
SELECT distinct CATEGORY
FROM tb_department;

-- 10번 문제

SELECT   STUDENT_NO
		,STUDENT_NAME 
        ,STUDENT_SSN
FROM tb_student
WHERE ABSENCE_YN = 'N' AND ENTRANCE_DATE like '__19%' AND STUDENT_ADDRESS like '%전주%';


  
